### ISSUE TITLE
equation error in lecture4.pdf page 12

### ISSUE THREAD

**Issue by yupbank** [dlsys-course/dlsys-course.github.io#1]
\bar{v0} = \bar{v_{0}'}+\bar{v_2}*\frac{\partial{v_2}}{\partial{v_0}} =  \bar{v_{0}'} +frac{ \bar{v_2}} {v_0}

\bar{v1} = \bar{v_{1}'}+\bar{v_3}*\frac{\partial{v_3}}{\partial{v_1}} =  \bar{v_{1}'} + \bar{v_3}*v_0

\bar{v2} = \bar{v5} * \frac{\partial{v5}}{\partial{v2}}

**Comment by icemelon** [comment]
Thanks. This is fixed.

**Comment by yupbank** [comment]
👍
